version: '2'
services:
    testjhipster2-app:
        image: testjhipster2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://testjhipster2-mysql:3306/testjhipster2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testjhipster2-mysql:
        extends:
            file: mysql.yml
            service: testjhipster2-mysql
